Capstone.Web/Controllers/HomeController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class HomeController : Controller
    {
        private IParkDAL dal;
        public HomeController(IParkDAL dal)
        {
            this.dal = dal;
        }
        

        // GET: Home
        public ActionResult Index()
        {
            List<Park> model = dal.GetAllParks();
            return View("Index", model);
        }
    }
}

Capstone.Web/Controllers/ParkController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class ParkController : Controller
    {
        private IParkDAL dal;
        public ParkController(IParkDAL dal)
        {
            this.dal = dal;
        }

        // GET: Park
        public ActionResult Detail(string id)
        {
            Park p = dal.GetPark(id);
            List<Weather> w = dal.GetWeather(id);
            PW pw = new PW(p, w);
            return View("Detail", pw);
        }

    }
}

Capstone.Web/Views/Home/Index.cshtml
@using Capstone.Web.Models;
@model List<Park>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach(var p in Model)
{
    <div>
        <a href="@Url.Action("Detail", "Park", new {id = p.ParkCode})">
            <div><img src="@Url.Content("~/Content/img/" + p.ParkCode + ".jpg")" alt="@p.ParkName" /></div>
            <div>@p.ParkName</div>
        </a>
        <div>@p.ParkDescription</div>
    </div>
}