Capstone.Web/Controllers/SurveyController.cs
using Capstone.Web.DAL;
using Capstone.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Web.Controllers
{
    public class SurveyController : Controller
    {
        private IParkDAL dal;
        public SurveyController(IParkDAL dal)
        {
            this.dal = dal;
        }
        // GET: Survey
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TakeSurvey()
        {
            Park model = new Park();
            return View("TakeSurvey", model);
        }
        [HttpPost]
        public ActionResult TakeSurvey(Park completedSurvey)
        {
            dal.SaveSurvey(completedSurvey);
            return RedirectToAction("SurveyResult");
        }
        public ActionResult SurveyResult(List<Park> model)
        {
            List<Park> model2 = dal.GetSurveyResults();
            return View("SurveyResult", model2);
        }
    }
}

Capstone.Web/Views/Survey/SurveyResult.cshtml
@using Capstone.Web.Models;
@model List<Park>
@{
    ViewBag.Title = "SurveyResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FavoriteParks</h2>
@foreach(var s in Model)
{
    <h2>
        @s.Total - @s.ParkCodeSurvey
    </h2>

}

Capstone.Web/Views/Survey/TakeSurvey.cshtml
@using Capstone.Web.Models;
@model Park
@{
    ViewBag.Title = "TakeSurvey";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TakeSurvey</h2>

<form action="@Url.Action("TakeSurvey", "Survey")" method="post">
    <div>
        @Html.LabelFor(m => m.EmailAddress)
        @Html.TextBoxFor(m => m.EmailAddress)
    </div>
    <div>
        <label for="Park"> State of Residence</label>
        @Html.DropDownListFor(m => m.StateSurvey, Model.States)
    </div>
    <div>
        <label for="Park">Activity Level</label>
        @Html.RadioButtonFor(m=> m.ActivityLevel, "inactive", false) inactive
        @Html.RadioButtonFor(m => m.ActivityLevel, "sedentary", false) sedentary
        @Html.RadioButtonFor(m => m.ActivityLevel, "active", false) active
        @Html.RadioButtonFor(m => m.ActivityLevel, "extremely active", false) extremely active
    </div>
    <div>
       <label for ="Park">Favorite Park</label>
        @Html.DropDownListFor(m => m.ParkCodeSurvey, Model.ParkNames)
    </div>

    <button>Submit!</button>

</form>